name: first file

on: 
  push:
    branches:
    - main


jobs: 

  firstjob: 
    runs-on: ubuntu-latest

    steps:
      - name: greeting
        run: echo "Hello Muhammad!! Github Actions First File"
